{% set name = "weasel" %}
{% set version = "0.1" %}
{% set sha256 = "78891f9fa68fc67e7eb0a93df35479b911d6a04a3790e64f8f73c0fda2f8162e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/michauhl/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  number: 0
  noarch: python
  script: $PYTHON -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - weasel.py -h

about:
  home: https://github.com/michauhl/weasel
  license: MIT
  license_file: LICENSE
  summary: Cornholio
