{% set name = "weasel" %}
{% set version = "0.3" %}
{% set sha256 = "d0ec0229e77b293df440fa5d257e40b15fc7d914f1a9a0adb2c321d1badd2bc7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/michauhl/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  number: 0
  noarch: python
  script: $PYTHON -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - weasel.py -h

about:
  home: https://github.com/michauhl/weasel
  license: MIT
  license_file: LICENSE
  summary: Cornholio
